# Default values for dronescheduler.
replicaCount: 3
identity:
  clientid:
  resourceid:
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
keyvault:
  uri:
reason: unknown
telemetry:
  level: "Error"
resources:
  requests:
    cpu: 450m
    memory: 350Mi
  limits:
    cpu: 600m
    memory: 500Mi
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false
