# Staging values for workflow.
nameOverride: workflow
exports:
  data:
    replicaCount: 3
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new staging deploy"
