# Staging values for package.
nameOverride: package
exports:
  data:
    replicaCount: 3
    image:
      pullPolicy: Always
    log:
      level: "info"
    reason: "new staging deploy"
    current: true
