# Production values for delivery.
nameOverride: delivery
exports:
  data:
    replicaCount: 3
    image:
      pullPolicy: IfNotPresent
    telemetry:
      level: "Error"
    reason: "new prod deploy"
