# QA values for delivery.
nameOverride: delivery
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new qa deploy"
    current: true
