# Default values for dronedelivery.
nameOverride: delivery
replicaCount: 1
identity:
  clientid:
  resourceid:
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
cosmosdb:
  id:
  collectionid:
keyvault:
  uri:
telemetry:
  level: "Error"
reason: unknown
resources:
  requests:
    cpu: 350m
    memory: 350Mi
  limits:
    cpu: 500m
    memory: 500Mi
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false
