# Default values for package service.
nameOverride: package
replicaCount: 1
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
log:
  level: error
cosmosDb:
  collectionName:
resources:
  requests:
    cpu: 300m
    memory: 100Mi
  limits:
    cpu: 410m
    memory: 140Mi
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false
