# Dev values for dronescheduler.
nameOverride: dronescheduler
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new dev deploy"
    current: true
